
GET  http://localhost:4000/notes
###
GET http://localhost:4000/notes/id/6328c82d667851cfc492d
###

GET http://localhost:4000/notes/title/test123

###

GET http://localhost:4000/notes/content/note123

###

POST http://localhost:4000/notes 
content-type: application/json

{ 
"title": "testnote",
"content": "tes"
}

###
PUT http://localhost:4000/notes/6328c82d667851cfc492dfca
content-type: application/json

{ 
"title": "checking timestamp on update",
"content": "timestamp on updateeeeeeeeeeddddd"
}

###
DELETE http://localhost:4000/notes/632bc7bcb78fc7813a16f331