
GET  http://localhost:4000/notes
###
GET http://localhost:4000/notes/id/6330fdff600d9b1dad39ba49
###

GET http://localhost:4000/notes/title/testnote12345

###

GET http://localhost:4000/notes/body/

###

POST http://localhost:4000/notes 
content-type: application/json

{ 
"title": "testnote12345",
"content": "testing note"
}

###
PUT http://localhost:4000/notes/6330fdff600d9b1dad39ba49
content-type: application/json

{ 
"title": "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
"content": "updated this note to contain english"
}

###
DELETE http://localhost:4000/notes/632f12031deb08a162231c2c