service: Dom-Devs-Node-REST-API

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: eu-west-2
  memorySize: 128
  timeout: 15

functions:
  Rest-API:
    handler: src/app.server # reference the file and exported method
    name: Dom-Devs-Node-REST-API
    events: # events trigger lambda functions
      - http: # this is an API Gateway HTTP event trigger
          path: /
          method: ANY
          cors: true
      - http: # all routes get proxied to the Express router
          path: /{proxy+}
          method: ANY
          cors: true
    environment:
      MONGO_URL: ${env:MONGO_URL}
      MONGO_URI: ${env:MONGO_URI}

plugins:
  - serverless-plugin-typescript
  - serverless-dotenv-plugin

useDotenv: true
